spring.application.name=speed-violation-service

server.port=${SERVER_PORT:8080}

velsis.violation.tolerance-margin-kmh=${TOLERANCE_MARGIN_KMH:7}
velsios.violation.tolerance-margin-percentage=${TOLERANCE_MARGIN_PERCENTAGE:7}
velsis.violation.percentage-threshold=${PERCENTAGE_THRESHOLD:100}
