spring.application.name=speed-violation-service

server.port=${SERVER_PORT:8080}
server.servlet.context-path=/api

springdoc.swagger-ui.path=/docs

velsis.violation.tolerance-margin-kmh=${TOLERANCE_MARGIN_KMH:7}
velsis.violation.tolerance-margin-percentage=${TOLERANCE_MARGIN_PERCENTAGE:7}
velsis.violation.percentage-threshold=${PERCENTAGE_THRESHOLD:100}
